name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install depenedencies
        run: sudo npm i -g typescript @vercel/ncc
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.BOT_TOKEN}}
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        run: |
          git config user.name "${{secrets.BOT_USERNAME}}"
          git config user.email "${{secrets.BOT_USERNAME}}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "[AUTO] Update generated code"
            git push
          fi

  test:
    needs: deploy-action-code
    strategy:
      matrix:
        os: [ macos-11, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        if: runner.os == 'macOS'
        with:
          xcode-version: ^12.5
      - name: Install Swift
        if: runner.os == 'Linux'
        uses: sersoft-gmbh/SwiftyActions@v1.3
        with:
          release-version: 5.4
          github-token: ${{secrets.GITHUB_TOKEN}}
      - uses: sersoft-gmbh/swift-version-action@main
        id: swift-version
      - name: Check for reported version
        run: swift --version | grep -q '${{steps.swift-version.outputs.version}}'
